---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: taxi-db
  namespace: taxi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCjaSAxcFZaVJGqAJ7sXDkHhRWMMjfVGfBe7WcbEpxhBFnTj0KgDKo9Vl7dxU5uA5tWGQwOXDWFh7NQ4v+T4odeU18rwii5P6cz5/9srvWFFEao7iGamcPtEJY/gLMxgsgB2a8vZEvBGk8xX/ZHfp2Rv8IhLJm3fd/nj1hiTv3iim4kbgXKDsHy7Xg3dFIszhBTGPE2ZsfOArd56AFIbLouILaTv3PcLTckj7WsjiHI4wPF2B96Fo8OJaVrI749hNwD74EQH1nfeSfQ44mE1rj+qHj1aMB5OJkptgFnRvjU79dfvmMIv3qqyNiaPQdf9tfkbbUtcM9IuLylIIFhkCtGxoep/auj+5JRs1ui3/efrgMY/pfsYRJMZ69hd/fb1CsIuD7jN04ZmGyiaIYRDPP0sSN89l2ctb/jyjnYXiK6+wk7TYu0tl3o4EXc3/PZJkmhQBtkE0vV+FXyzKPKyFnXs0QrPuffSDByHH9FcGcnI/x/ey0pYKHhj26xlKPCBDRYyyXjNTkjbsgH3IWlZL/Q/+vAvKCLaz0XpMDdkctmbSsvRUBTjbAxZCURKrNixEAB4fNQyhJsGpNTHTZvEpq/art1tdV2MiNlAmX7QZxZEneps0XIZ0ebE+OTuuOEXN9bzSBbnta20KtAlQDWrqsYzz6/Pt2WVdYdgCzH1ourmSi4WXT+chPFKdtqSIm1H7Gpfs7ieJ0Pqc7WoCJtMlyrqg33Pp+mv6z7S5Ny0NdTbb8baFkG2mBT
    DB_USERNAME: AgAS5skDORVsLkagEr5Isly0ZvkhX0SfaAxUjSg1STBaUjlfCR6Vj6/Se7uIsGzGQUw22ChfUhQQeSttwCFM7B4HA3cIhzgwsy/MA2hw6uiD+ozlaEWkwyypffSr423ARPp0WNCAfoQgIE3b+XDp9avb66QXSTRDJiu3GOkDdVjKdVxxtaAf+0aIWsireh98VIVjP/QLBD9EXSZHiyjg+8x8L/bAiE6Q3BAfDf2A9t8QeUBVNoxx9PuGnQueJAhdI0tIpnUtfV2GpenEQexFHGaGC7MwhRUwfBHRNXZPgxmOs7GuoAwdbWHsUoSyV/EzTbT5WuA49UAjGJ34OEmL7mwmmaLr69+sV5dh8J8Izy3t54DmNzd7NIgxG9H1okXCr4RcdRXKNkmXjcRaU0X8JeVo8UOLpFQ3GO8PfJNyG2QQSKwhz+/9C56HXG0IWk5O+9YmZattK0sq75KF75m3w78HKiZ8ODjyrk9qajVG3LCbcnnRIv8M4q/dDC0tKun3SDmInnbzipqMtzsMHqYQwcccDvdYEmJNKp7wWzX1U0j+0iEvoJQtLqCFIEcn16W6WBjEhpeuwfPigMe0Vu014MXOyccvQNNvUC3JdBnN7kz8v5OLyh4L3Ql2YFgj2LHnqUiIH22a+CpnX+29zBYi4NAVgj5COfwCUvxO48ltvX/qGGVIv2rmQOYN8nY5OJoYeJCKZrZba/CtMls=
  template:
    metadata:
      name: taxi-db
      namespace: taxi-prod
