---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: taxi-db
  namespace: taxi-dev
spec:
  encryptedData:
    DB_PASSWORD: AgAs6AV7LKuIeMSpCH2vAoRhj6WXvEcgLOJ7Jvohvhsyu1C4qbCCfzMM4QVI6GVBr2B9kntcL/zryp+ueSCEXykUCoSZ6ano8uGPHTtW6Wp7Ri/k6oEgYnfei8EnJJeKOuPhQLLgFEO57o14kbEci3DvulYTH+gYjhigtRdTANvtVI3i1nojzye7obgLywCBfOTPPha1gjcCZYU8q7gjW42GSGWjK7kUkiJSUzllY10jiG+v5ovCOBlTa1YMqhwPZEdNlY21V0m2XNCEcuCSjGkO6kNOA6jdh39TUfo+2eyZUOnMl8g8mdXflPIMF9Q4rpuuTXBxvKmU6z+he97n+inRfBQgIT33HwH4moQQBWsadEJsQMofANSglkSRWvgukHf8mK4BL3W8CiSQgx1ju4pecXoNM8FcHdpLuiQ+NNp6XvUc/oasnpnF18GuR5U2h0sPFfzsdypYTKVYClyVv7eo03URtU6CmFcgsBAKkvkgSR9o5Sgs+81x163C5rHwV1EztWNT/Bt/Mmqt0R2KB45jNiW8RBhMxVKNyVxekHlKp6htneszrxkMm2AhH6B5GNZNLVLMolazQZkmqpOjVvcqwzDf1tsBQRqtvQIB3KS+1UTqOoXJ4S4Olq2GYzJ47VL4qyiAU2zwH6iEjP+CMZfCQdjHjdrKujDJ+MmFB5PzhsDx28WpTYJR2dnFIE5cn7ufDBzRPsFK819pp7B9WoBXBKLFeXSmKZtjKofQnQQjoS8jVjvEyf0d
    DB_USERNAME: AgBSwa/fh9LB/dzyxaEO9GoB+qMDriUc5CgI5/VvMWTX/pKDGdWwfVRwr9OHHCwLKOmVviJFZ2gy7L5LLFNX14zsQertdkhhT6PrwEUeNj/TZ/TLUcYWNl2uKoBYdb25ADaGffO0Fcrsc2lXLN2JIpSMqOQ2XtNU/Sd+a/HDj5ISRI7WxYjOTxncHR3xHG1Ttk6lH4G5hnY5sjj3wSOILIgNvacM9geulZvyJiTTYelJEjR8MtJFjArPVpmjf241HlOs56+PTU29016pKbz6wUkZ1y5c+gjxSfjEdqpcOhF220crME2kg50skTJYJWv7oY13jZ9BOy74+kefIknN08sYq/UagksKOpc1PrwWptWzBoS1nzmYzCDWed0SSpNTlBv+FFaNrhCjqbxUYAuY4OyaXXthnVZzOGaQgf9jIpsEH1WTzlpjnm4RhwkEEsCFd5tQXoFt0vRxqI31tPoRSpjXTgi+g7Ewb/L908yZPA5omiLDvA/zFWw8i1AZSVU2sksknOZRTeM2ls5d/ucgKe0AcF6eSezsDNcM+cJem3kcMVBlgTn3521OfXTIg7+vvqro8D0yBbsOiOqtY+/vfTiljZKlwfuomBBvWvFa2T4Q56bCJD9tsXxBhA/nFM+Au/+CNoHnK4Oa73Kt4fLmdr60LvkDTy+D351ucsngA/uGaZK/QztxMqgwJ5hxLz9z1g/FS9QBMNSiUg==
  template:
    metadata:
      name: taxi-db
      namespace: taxi-dev
